version: '3'
services:
  web:
    build:
      # the folder that holds all the files for your project
      context: .
      # the file to be used to build the image for this service
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  # essentially the same as the web service, but with the startup command overridden
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # overrides the Startup Command specified in the Dockerfile.dev
    command: ['npm', 'run', 'test']
